# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.City')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.CharField(max_length=200)),
                ('ends_at', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('image_list', models.URLField(blank=True)),
                ('is_active', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.City')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
